# IBM Developer Skills Network

# Linear Regression 1D: Prediction

In [1]:
import torch

# Prediction

In [2]:
# Define w=2, b=-1 for y=wx+b  - weight and bias
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [3]:
# Function for prediction
def forward(x):
    yhat = w*x + b
    return yhat

In [4]:
# Make a prediction
x = torch.tensor([[1.0]])
yhat = forward(x)  # 2*1 - 1 = 1
print('yhat=',yhat)

yhat= tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
# Multiple input prediction
x = torch.tensor([[1.0], [2.0]])
print('shape x:', x.shape)

shape x: torch.Size([2, 1])


In [6]:
yhat = forward(x)
print('yhat=', yhat)

yhat= tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [8]:
# Practice
x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = forward(x)
print('yhat=', yhat)

yhat= tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


# Class Linear

In [9]:
from torch.nn import Linear

In [10]:
# Set random seed
torch.manual_seed(1)  # random will produce same result everytime

Let us create the linear object by using the constructor. The parameters are randomly created. <br> Let us print out to see what w and b. The parameters of an torch.nn.Module model are contained in the model’s parameters accessed with lr.parameters():

In [11]:
lr = Linear(in_features=1, out_features=1, bias=True)
print('parameter w, b =', list(lr.parameters()))

parameter w, b = [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


w = 0.5153,  b = -0.4414

In [12]:
print('weight=', lr.weight)
print('bias=', lr.bias)

weight= Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias= Parameter containing:
tensor([-0.4414], requires_grad=True)


In [13]:
# Make a prediction
x = torch.tensor([[1.0]])
yhat = lr(x)
print('The prediction: ', yhat)

The prediction:  tensor([[0.0739]], grad_fn=<AddmmBackward>)


In [14]:
# 2 input
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print('The prediction: ', yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


In [15]:
# Practice
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print('The prediction: ', yhat)

The prediction:  tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


# Build Custom Modules

In [16]:
from torch import nn

In [17]:
# Custom class module
class LR(nn.Module):

    # Constructor
    def __init__(self, input_size, output_size):

        # Inherit from parent
        super(LR, self).__init__()  # Allow access to parent class method - can be super().__init__() - not need LR, self
        self.linear = nn.Linear(input_size, output_size)

    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out


In [18]:
# Create the linear regression model
lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [19]:
# Make a prediction
x = torch.tensor([[1.0]])
yhat = lr(x)
print('yhat=', yhat)

yhat= tensor([[0.2755]], grad_fn=<AddmmBackward>)


In [20]:
# Multiple sample
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print('yhat=', yhat)

yhat= tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward>)


The parameters are also stored in an ordered dictionary

In [21]:
print("Python dictionary: ", lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.1939]])), ('linear.bias', tensor([0.4694]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.1939]]), tensor([0.4694])])


In [22]:
# Practice
x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = lr(x)
print('yhat=', yhat)

yhat= tensor([[ 0.2755],
        [ 0.0816],
        [-0.1122]], grad_fn=<AddmmBackward>)
