# IBM Developer Skills Network

# Multiple Linear Regression

In [1]:
import torch
from torch import nn
torch.manual_seed(1) # force random to give out same value everytime

# Prediction

In [5]:
# Set the weight and bias
w = torch.tensor([[2.0], [3.0]], requires_grad=True)
b = torch.tensor([[1.0]], requires_grad=True)

In [6]:
# Define the prediction function
def forward(x):
    yhat = torch.mm(x, w) + b  # matrix dot product between x and w
    return yhat

In [7]:
# calculate yhat

x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print("The result: ", yhat)

The result:  tensor([[9.]], grad_fn=<AddBackward0>)


# Multiple x samples

In [8]:
X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])
yhat = forward(X)
print('yhat=',yhat)

yhat= tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


# CLass Linear

In [9]:
# Create a linear model
model = nn.Linear(2, 1)  # w and b are randomly generated

In [10]:
# Make a prediction of x
yhat = model(X)
print('The result is ', yhat)

The result is  tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward>)


# Build Custom Modules

In [11]:
# Create linear regression class

class linear_regression(nn.Module):
    # Constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    # Prediction
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [12]:
# build an object
model = linear_regression(2, 1)  # 2 input 1 output

In [13]:
# print the parameters
print('parameters are ', list(model.parameters()))

parameters are  [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


w1 = 0.3319, w2 = -0.6657, b = 0.4241

In [14]:
# using state_dict
model.state_dict()

OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])),
             ('linear.bias', tensor([0.4241]))])

In [15]:
# Make a prediction
yhat = model(x)
print('yhat=', yhat)

yhat= tensor([[-0.5754]], grad_fn=<AddmmBackward>)


In [16]:
yhat = model(X)
print('yhat=', yhat)

yhat= tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward>)


In [17]:
# Practice
X = torch.tensor([[11.0, 12.0, 13, 14], [11, 12, 13, 14]])

In [18]:
# build an object
model = linear_regression(4, 1)  # 4 input 1 output

In [19]:
yhat = model(X)

In [20]:
yhat

tensor([[2.1062],
        [2.1062]], grad_fn=<AddmmBackward>)